### PR TITLE
Print CPU instruction set in CI

### PR DESCRIPTION
**Pull request by wenleix**
Summary:
We see "illegal instruction" error few times on CI (which is not reproducible).  We suspect it's due to it happened to be run a CPU without AVX support.  (https://stackoverflow.com/questions/37480071/how-to-tell-if-a-linux-machine-supports-avx-avx2-instructions)

Print the instruction set to help debug.

Differential Revision: D32707568

### CODE REVIEW

**Review by ejguan — APPROVED** [review]
LGTM

**Comment by wenleix** [comment]
Here is the failed information :

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
stepping	: 2
microcode	: 0xffffffff
cpu MHz		: 2397.220
cache size	: 30720 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 15
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt md_clear
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 4794.44
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

E5-2673 is a processor launched on 2013 (https://ark.intel.com/content/www/us/en/ark/products/79930/intel-xeon-processor-e52673-v2-25m-cache-3-30-ghz.html)  .But supports avx/avx2

**Comment by ejguan** [comment]
Can this be a problem from ccache?

**Comment by wenleix** [comment]
@ejguan : possibly. I also note the CXX FLAGS is different from Velox now (it used to copy from Velox but velox updates its CXX FLAG)

https://github.com/facebookresearch/torcharrow/blob/1fac1441cd89a8ea8f63300d8be7148295b30014/csrc/velox/CMakeLists.txt#L17-L18

Here is latest Velox CXX FLAGS

https://github.com/facebookincubator/velox/blob/282b228c303b4410352806d7a807fee9b965ae06/CMakeLists.txt#L125-L127

Not sure if `-march=native` would help...

**Comment by wenleix** [comment]
Here is a comparison of flags in success and failed:
```python
>>> a = "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xsaves md_clear".split(" ")

>>> b = "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt md_clear".split(" ")

>>> set(a) - set(b)
{'3dnowprefetch', 'rdseed', 'avx512vl', 'xsavec', 'xsaves', 'hle', 'avx512dq', 'mpx', 'avx512cd', 'avx512bw', 'rtm', 'avx512f', 'clflushopt', 'adx', 'smap'}
```

**Pull request closed without merging**
