### PR TITLE
Using coalesce for fill_null

### PR DESCRIPTION
**Pull request by bearzx**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #259

Differential Revision: [D35158061](https://our.internmc.facebook.com/intern/diff/D35158061)

### CODE REVIEW

**Comment by bearzx** [comment]
dropping because of duplicate with #260

**Review by wenleix — APPROVED** [review]

**Comment by bearzx** [comment]
@bearzx has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35158061).

**Comment by bearzx** [comment]
@bearzx has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35158061).

**Comment by bearzx** [comment]
closing because of duplicates in #268

**Pull request closed without merging**
